jm_lms/apps/courses/urls.py
from django.conf.urls import patterns, url

from .views import  (CourseListView, 
                    CourseDetailView, 
                    ModuleListView, 
                    ModuleDetailView, 
                    LessonCreateView, 
                    LessonDetailView,
                    EnrolUserTemplateView)


def course_url(path):
    return r'^(?P<course_slug>[-\w\d]+){}'.format(path)
    
def module_url(path):
    return course_url(r'/(?P<module_slug>[-\w\d]+){}'.format(path))
    
def lesson_url(path):
    return module_url(r'/(?P<lesson_slug>[-\w\d]+){}'.format(path))

urlpatterns = patterns('',
    url(r'^$', CourseListView.as_view(), name='course_list'),
    url(course_url('/$'), CourseDetailView.as_view(), name='course_detail'),
    url(r'^module/$', ModuleListView.as_view(), name='module_list'),
    url(module_url('/$'), ModuleDetailView.as_view(), name='module_detail'),
    url(module_url('/lesson/create$'), LessonCreateView.as_view(), name='lesson_create'),
    url(module_url('/(?P<lesson_slug>[-\w\d]+)$'), LessonDetailView.as_view(), name='lesson_detail'),
    url(r'^enrol/(?P<userid>\d+)/(?P<courseid>\d+)/$', EnrolUserTemplateView.as_view(), name='enrol_to_course'),
)

jm_lms/apps/homesite/urls.py
from django.conf.urls import patterns, url

from .views import (home_page)


urlpatterns = patterns('',
    url(r'^$', home_page, name='homepage'),
)

jm_lms/apps/quiz/urls.py
from django.conf.urls import patterns, url

from .views import QuizListView, CategoriesListView,\
    ViewQuizListByCategory, QuizUserProgressView, QuizMarkingList,\
    QuizMarkingDetail, QuizDetailView, QuizTake


urlpatterns = patterns('',

                       url(regex=r'^$',
                           view=QuizListView.as_view(),
                           name='quiz_index'),

                       url(regex=r'^category/$',
                           view=CategoriesListView.as_view(),
                           name='quiz_category_list_all'),

                       url(regex=r'^category/(?P<category_name>[\w.-]+)/$',
                           view=ViewQuizListByCategory.as_view(),
                           name='quiz_category_list_matching'),

                       url(regex=r'^progress/$',
                           view=QuizUserProgressView.as_view(),
                           name='quiz_progress'),

                       url(regex=r'^marking/$',
                           view=QuizMarkingList.as_view(),
                           name='quiz_marking'),

                       url(regex=r'^marking/(?P<pk>[\d.]+)/$',
                           view=QuizMarkingDetail.as_view(),
                           name='quiz_marking_detail'),

                       #  passes variable 'quiz_name' to quiz_take view
                       url(regex=r'^(?P<slug>[\w-]+)/$',
                           view=QuizDetailView.as_view(),
                           name='quiz_start_page'),

                       url(regex=r'^(?P<quiz_name>[\w-]+)/take/$',
                           view=QuizTake.as_view(),
                           name='quiz_question'),
)

jm_lms/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView

from apps.accountusers.views import LoginView, LogoutView, RegisterView, EmailSentView, ActivationView, NewUserRegistrationAPI
from apps.registrations.views import ProspectiveUserList, ProspectiveUserDetail


urlpatterns = [
    # Examples:
    # url(r'^$', 'project_name.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    
    url(r'^summernote/', include('django_summernote.urls')),
    
    # Pesapal processing url
    url(r'^payments/', include('django_pesapal.urls')),
    
    #url(r'^$', TemplateView.as_view(template_name='homepage.html')),
    
    url(r'^', include('jm_lms.apps.homesite.urls', namespace='home')), # Directing root url to a different app
    url(r'^dashboard/', include('jm_lms.apps.dashboard.urls')),
    url(r'^course/', include('jm_lms.apps.courses.urls')),
    url(r'^exercise/', include('jm_lms.apps.exercises.urls')),
    url(r'^purchase/', include('jm_lms.apps.purchase.urls', namespace='purchase')),
    url(r'^askaquestion/', include('jm_lms.apps.askaquestion.urls', namespace='askaquestion')),
    
    # user authentication and registration
    url(r'^login/', LoginView.as_view(), name='login'),
    url(r'^logout/', LogoutView.as_view(), name='logout'),
    url(r'^register/', RegisterView.as_view(), name='register'),
    url(r'^registration_email_sent\.html', EmailSentView.as_view(), name='confirmation_mail_sent'),
    url(r'^user_activation\.html', ActivationView.as_view(), name='activation'),
    url(r'^terms_and_conditions\.html', TemplateView.as_view(template_name='terms_conditions.html')),
    
    # Quiz links
    url(r'^quiz/', include('jm_lms.apps.quiz.urls')),
    
    # REST API for new signups
    url(r'^pusers/', ProspectiveUserList.as_view()),
    url(r'^pusers/(?P<pk>[0-9]+)/$', ProspectiveUserDetail.as_view()),
    url(r'^newreg/', NewUserRegistrationAPI.as_view()),

    url(r'^admin/', include(admin.site.urls)),
]

jm_lms/apps/analytics/models.py
from django.db import models

# Create your models here.

jm_lms/apps/courses/models.py
import logging

from django.conf import settings
from django.db import models
from django.db.models import Sum
from django.template.defaultfilters import slugify
from django.utils.translation import ugettext_lazy as _

from positions.fields import PositionField

from jm_lms.apps.exercises.models import Exercise
from jm_lms.apps.quiz.models import Quiz



log = logging.getLogger(__name__)


NOT_STARTED = 0
IN_PROGRESS = 1
COMPLETED = 2
PROGRESS_STATUS = (
    (NOT_STARTED, _("Not Started")),
    (IN_PROGRESS, _("In Progress")),
    (COMPLETED, _("Completed"))
)


class Course(models.Model):
    """
    Data model representing a course.
    A course can have one or more modules.
    """
    name = models.CharField(verbose_name=_("Course Name"), max_length=200, help_text=_('The course title'))
    description = models.TextField(verbose_name="Course Description", help_text=_("Course description"))
    prerequisite = models.ForeignKey('self', verbose_name=_("Prerequisite Course"), null=True, blank=True, default=None)   
    slug = models.SlugField(editable=False, help_text=_('Unique identifier'))
    position = PositionField(collection='prerequisite')
    position_order = models.IntegerField(verbose_name=_("Order to be shown in views"), default=0)
    
    class Meta:
        verbose_name_plural = "Courses"
        
    def __unicode__(self):
        return self.name
        
    def get_absolute_url(self):
        return reverse('course_detail', args=[self.slug])
        
    def save(self, *args, **kwargs):
        if not self.id:
            slug = slugify(self.name)
            new_slug = slug
            count = 0
            while Course.objects.filter(slug=new_slug).exclude(id=self.id).count() > 0:
                count += 1
                new_slug = '{slug}-{count}'.format(slug=slug, count=count)
            self.slug = new_slug
            
        super(Course, self).save(*args, **kwargs)
        
    @property    
    def previous_course(self):
        if self.prerequisite is None:
            return Course.objects.None()
        return self.prerequisite
        
    def _student_count(self):
        raise NotImplementedError
        
    @classmethod
    def get_student_progress_in_course(cls, student, course):
        """
        Calculates the progress of the given student in a particular course.
        This is achieved by summing up the module progress of the student.
        """
        progress = 0
        try:
            course = Course.objects.get(pk=course.pk)
            course_modules = course.module_set.all()
            num_of_modules_in_course = course_modules.count()
            
            # Current progress of all the modules done by a student
            curr_module_progress_total = 0
            for module in course_modules:
                curr_module_progress_total += Module.get_student_progress_in_module(student, module)
                
            # Calculate current course progress of the student
            progress = (100*curr_module_progress_total)/(num_of_modules_in_course*100)
        except ZeroDivisionError:
            progress = 0
        return progress
        
    @property    
    def has_previous_course(self):
        if self.prerequisite:
            return True
        return False
        
    def is_previous_course_done(self, student):
        """
        Determine if a previous course has been completed by student.
        """
        if not self.has_previous_course:
            return True
        elif self.has_previous_course:
            try:
                total_course_score = StudentLessonProgress.objects.filter(student=student, lesson__module__course=self.prerequisite).aggregate(total_percentage=Sum('done_percent'))
                course_score_result = total_course_score.get('total_percentage', 0)
                
                student_course_progress = (course_score_result*100) / (self.prerequisite.module_set.all().count()*100)
                
                if student_course_progress >= 100:
                    return True
            except (StudentLessonProgress.DoesNotExist, ZeroDivisionError, TypeError):
                return False            
        return False
    

class Module(models.Model):
    DRAFT = 1
    SUSPENDED = 2
    PUBLISHED = 3
    MODULE_STATUSES = (
        (DRAFT, _("Draft")),
        (SUSPENDED, _("Suspended")),
        (PUBLISHED, _("Published"))
    )
    course = models.ForeignKey(Course)
    name = models.CharField(verbose_name=_("Module Name"), max_length=200, help_text=_('The module title'))
    description = models.TextField(verbose_name="Module Description", help_text=_("Module description"))
    prerequisite = models.ForeignKey('self', verbose_name=_("Prerequisite Module"), null=True, blank=True, default=None)   
    slug = models.SlugField(editable=False, help_text=_('Unique identifier'))
    status = models.IntegerField(verbose_name="Module Status", choices=MODULE_STATUSES, default=PUBLISHED)
    position = PositionField(collection='course', default=0)
    end_of_module = models.TextField(verbose_name=_("Module Summary"), default=None, null=True, help_text=_("Wrap and summarize this module"))
    last_module = models.ForeignKey('self', verbose_name=_("Previous Module"), null=True, blank=True, default=None, related_name="previous_module")
    next_module = models.ForeignKey('self', verbose_name=_("Next Module"), null=True, blank=True, default=None, related_name="the_next_module")
    

    class Meta:
        verbose_name_plural = "Modules"
        
    def __unicode__(self):
        return self.name
        
    def get_absolute_url(self):
        return reverse('module_detail', args=[self.slug])
        
    def save(self, *args, **kwargs):
        if not self.id:
            slug = slugify(self.name)
            new_slug = slug
            count = 0
            while Module.objects.filter(slug=new_slug).exclude(id=self.id).count() > 0:
                count += 1
                new_slug = '{slug}-{count}'.format(slug=slug, count=count)
            self.slug = new_slug           
            
        super(Module, self).save(*args, **kwargs)
        
    @classmethod
    def get_student_progress_in_module(cls, student, module):
        """
        Calculates the progress of the given student in a particular module.
        This is achieved by summing up the lesson progress of the student.
        """
        progress = 0
        try:
            if module:
                module = Module.objects.get(pk=module.pk)
                module_lessons = module.lesson_set.all()
                num_of_lessons_in_module = module_lessons.count()
                # last_lesson_in_module = [index for index, item in enumerate(module_lessons)[len(module_lessons)-1::]]
                # a = module_lessons.order_by('id')
                # b = list(a.values_list('id', flat=True)).index(obj.id)
                # last_lesson = b[len(b)-1::]

                # Current progress of all the lessons done by a student
                curr_lesson_progress_total = 0
                for lesson in module_lessons:
                    curr_lesson_progress_total += Lesson.get_student_progress_in_lesson(student, lesson)

                # Calculate current module progress of the student
                progress = (100*curr_lesson_progress_total)/(num_of_lessons_in_module*100)
        except ZeroDivisionError, AttributeError:
            progress = 0
        return progress

    # @classmethod
    # def get_last_lesson_in_module(cls, student, module):
    #     last_lesson = Module.objects.raw(
    #         "select * from courses_lesson where module_id in (select module_id from courses_lesson group by module_idhaving count (*) > 1)"
    #      )
    #
    #     # if module:
    #     #     module = Module.objects.get(pk=module.pk)
    #     #     module_lessons = module.lesson_set.all()
    #     #     last_lesson_in_module = module_lessons[-1]
    #     return last_lesson

        
    @property    
    def has_previous_module(self):
        if self.prerequisite:
            return True
        return False

        
    def is_previous_module_done(self, student):
        """
        Determine if a previous module has been completed by student.
        """
        if not self.has_previous_module:
            return True
        elif self.has_previous_module:
            try:
                total_module_score = StudentLessonProgress.objects.filter(student=student, lesson__module=self.prerequisite).aggregate(total_percentage=Sum('done_percent'))
                module_score_result = total_module_score.get('total_percentage', 0)
                
                student_module_progress = (module_score_result*100) / (self.prerequisite.lesson_set.all().count()*100)
                
                if student_module_progress >= 100:
                    return True
            except (StudentLessonProgress.DoesNotExist, ZeroDivisionError, TypeError):
                return False            
        return False
        




class Lesson(models.Model):
    module = models.ForeignKey(Module)
    name = models.CharField(verbose_name=_("Lesson Title"), max_length=200, help_text=_('The lesson title'))
    prerequisite = models.ForeignKey('self', verbose_name=_("Prerequisite Lesson"), null=True, blank=True, default=None)   
    content = models.TextField()
    instructions_before = models.TextField(verbose_name=_("Instructions before exercise"), null=True, blank=True, default=None)
    instructions_after = models.TextField(verbose_name=_("Instructions after exercise"), null=True, blank=True, default=None)
    quizzes = models.ManyToManyField(Quiz, verbose_name=_("Quiz"), blank=True, related_name='lessons')
    slug = models.SlugField(editable=False, help_text=_('Unique identifier'))
    exercises = models.ManyToManyField(Exercise, verbose_name=_("Exercise"), blank=True, related_name='lesson_exercises')

jm_lms/apps/askaquestion/forms.py
from django.forms import ModelForm
from .models import QuestionAsked


class AskQuestionForm(ModelForm):
    class Meta:
        model = QuestionAsked
        fields = ['title', 'body', 'lesson']

jm_lms/apps/courses/forms.py
from django import forms

from .models import LessonQuestion

class LessonQuestionForm(forms.ModelForm):

    class Meta:
        model = LessonQuestion
        fields = ('title', 'description',)

jm_lms/apps/analytics/views.py
from django.shortcuts import render

# Create your views here.

jm_lms/apps/askaquestion/views.py
from django.core.urlresolvers import reverse, reverse_lazy
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from jm_lms.apps.courses.models import Lesson
from .forms import AskQuestionForm
from .models import QuestionAsked


def process_question_asked(request):
    if request.method == 'POST':
        askquestion_form = AskQuestionForm(request.POST, prefix='askquestion')
        if askquestion_form.is_valid():
            lesson = Lesson.objects.get(pk=askquestion_form.cleaned_data['lesson'].pk)
            question_asked = QuestionAsked(
                                title = askquestion_form.cleaned_data['title'],
                                body = askquestion_form.cleaned_data['body'],
                                sender = request.user,
                                lesson = lesson
                                )
            question_asked.save()
            return HttpResponseRedirect(reverse("learn_lesson", args=[lesson.module.course.slug, lesson.module.slug, lesson.slug]))
    return HttpResponseRedirect(reverse("student_dashboard"))
    
    
class QuestionAskedListView(ListView):

    model = QuestionAsked
    context_object_name = 'questions_asked'
    template_name = 'askaquestion/askedquestions_list.html'
    
    """def get_context_data(self, **kwargs):
        context = super(QuestionAskedListView, self).get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context"""
        
    def get_queryset(self):
        return QuestionAsked.objects.filter(sender=self.request.user)
        
        
class QuestionAskedDetailView(DetailView):

    model = QuestionAsked
    context_object_name = 'question_asked'
    template_name = 'askaquestion/askedquestion_detail.html'

    """def get_context_data(self, **kwargs):
        context = super(QuestionAskedDetailView, self).get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context"""
        

jm_lms/templates/course/course_detail.html
{% extends "base_generic.html" %}
{% load staticfiles %}

{% block title %}{{ course.name }}{% endblock %}

{% block body %}
<div id="contentwrapper">
    <div class="main_content">
        <div id="jCrumbs" class="breadCrumb module">
            <ul>
                <li>
                    <a href="{% url 'dashboard' %}"><i class="glyphicon glyphicon-home"></i></a>
                </li>
                <li>
                    <a href="{% url 'course_list' %}">Courses List</a>
                </li>
                <li>
                    {{ course.name }}
                </li>
            </ul>
        </div>	
        <div class="row">
            
            <div class="col-sm-12 col-md-12">
                <h3 class="heading">{{ course.name }}</h3>
                
                <div class="vcard">
					<img class="thumbnail" src="{% static 'img/empty_image.png' %}" alt="">
					<ul>
						<li class="v-heading">Course info</li>
						<li>
							<span class="item-key">Name</span>
							<div class="vcard-item">{{ course.name }}</div>
						</li>
						<li>
							<span class="item-key">Description</span>
							<div class="vcard-item">{{ course.description|safe }}</div>
						</li>
				    </ul>
				</div> 
				
				<h3 class="heading">Modules in {{ course.name }}</h3>
                
                
                <table class="table table-striped table-bordered table-condensed" data-rowlink="a">
                    <thead>
                        <tr>
                            <th>id</th>
                            <th>Name</th>
                            <th>Description</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for module in module_list %}
                    <tr>
                        <td>{{ module.id }}</td>
                        <td><a href="{% url 'module_detail' course.slug module.slug %}">{{ module.name }}</a></td>
                        <td>{{ module.description|truncatewords:20|safe }} [&hellip;]</td>
                        <td><a href="#">Edit</a> | <a href="#">Delete</a></td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            
            
        </div>                
    </div>
</div>
{% endblock body %}

jm_lms/templates/course/course_list.html
{% extends "base_generic.html" %}
{% load staticfiles %}

{% block title %}Courses List{% endblock %}

{% block body %}
<div id="contentwrapper">
    <div class="main_content">
        <div id="jCrumbs" class="breadCrumb module">
            <ul>
                <li>
                    <a href="{% url 'dashboard' %}"><i class="glyphicon glyphicon-home"></i></a>
                </li>
                <li>
                    Courses List
                </li>
            </ul>
        </div>	
        <div class="row">
            
            <div class="col-sm-12 col-md-12">
                <h3 class="heading">Courses List</h3>
                <table class="table table-striped table-bordered table-condensed" data-rowlink="a">
                    <thead>
                        <tr>
                            <th>id</th>
                            <th>Name</th>
                            <th>Description</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for course in course_list %}
                    <tr>
                        <td>{{ course.id }}</td>
                        <td><a href="{% url 'course_detail' course.slug %}">{{ course.name }}</a></td>
                        <td>{{ course.description|truncatewords:20 }} [&hellip;]</td>
                        <td><a href="#">Edit</a> | <a href="#">Delete</a></td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            
            
        </div>                
    </div>
</div>
{% endblock body %}

jm_lms/templates/course/lesson_create.html
{% extends "base_generic.html" %}
{% load staticfiles %}

{% block title %}Add New Lesson{% endblock %}

{% block body %}
<div id="contentwrapper">
    <div class="main_content">
        <div id="jCrumbs" class="breadCrumb module">
            <ul>
                <li>
                    <a href="{% url 'dashboard' %}"><i class="glyphicon glyphicon-home"></i></a>
                </li>
                <li>
                    <a href="{% url 'course_list' %}">Courses List</a>
                </li>
                <li>
                    <a href="{% url 'course_detail' module.course.slug %}">{{ module.course }}</a>
                </li>
                <li>
                    {{ module.name }}
                </li>
            </ul>
        </div>	
        <div class="row">
            
            <div class="col-sm-12 col-md-12">
                <h3 class="heading">Add New Lesson</h3>                
                
                <!--<form action="{% url 'lesson_create' module.course.slug module.slug %}" method="post" id="lesson_form" class="form-horizontal">
                    {% csrf_token %}
                    <div class="form-group">
						<label for="name" class="col-lg-2 control-label">Title</label>
						<div class="col-lg-8">
							<input type="text" name="name" id="id_name" class="form-control">
						</div>
					</div>
                    <div class="form-group">
						<label for="content" class="col-lg-2 control-label">Content</label>
						<div class="col-lg-8">
							<textarea name="content" id="id_content" cols="10" rows="16" class="tinymce form-control auto_expand" style="overflow: hidden; word-wrap: break-word; height: 54px;">
							</textarea>
						</div>
					</div>
                    <div class="form-group">
						<div class="col-lg-8 col-lg-offset-2">
							<button type="submit" class="btn btn-primary">Create</button>
						</div>
					</div>
                </form>-->
                {{ form.as_p }}
            </div>    
            
        </div>                
    </div>
</div>
{% endblock body %}

jm_lms/templates/course/lesson_detail.html
{% extends "base_generic.html" %}
{% load staticfiles %}

{% block title %}{{ lesson.name }}{% endblock %}

{% block body %}
<div id="contentwrapper">
    <div class="main_content">
        <div id="jCrumbs" class="breadCrumb module">
            <ul>
                <li>
                    <a href="{% url 'dashboard' %}"><i class="glyphicon glyphicon-home"></i></a>
                </li>
                <li>
                    <a href="{% url 'course_list' %}">Courses List</a>
                </li>
                <li>
                    <a href="{% url 'course_detail' lesson.course.slug %}">{{ lesson.course }}</a>
                </li>
                <li>
                    <!-- TODO: Add link to module detail in href -->
                    <a href="">{{ lesson.module }}</a>
                </li>
                <li>
                    {{ lesson.name }}
                </li>
            </ul>
        </div>	
        <div class="row">
            
            <div class="col-sm-12 col-md-12">
                <h3 class="heading">{{ lesson.name }}</h3>
                
                SOME LESSON CONTENT WILL GO HERE.</br>
                {{ lesson.content }}
                
                </br>
                
                <a href="" class="btn btn-default">Previous lesson:</a>
                <a href="" class="btn btn-default">Next lesson:</a>
                <a href="" class="btn btn-default">Start Quiz</a>
            </div>
            
            
        </div>                
    </div>
</div>
{% endblock body %}

jm_lms/templates/course/module_detail.html
{% extends "base_generic.html" %}
{% load staticfiles %}

{% block title %}{{ module.name }}{% endblock %}

{% block body %}
<div id="contentwrapper">
    <div class="main_content">
        <div id="jCrumbs" class="breadCrumb module">
            <ul>
                <li>
                    <a href="{% url 'dashboard' %}"><i class="glyphicon glyphicon-home"></i></a>
                </li>
                <li>
                    <a href="{% url 'course_list' %}">Courses List</a>
                </li>
                <li>
                    <a href="{% url 'course_detail' module.course.slug %}">{{ module.course }}</a>
                </li>
                <li>
                    {{ module.name }}
                </li>
            </ul>
        </div>	
        <div class="row">
            
            <div class="col-sm-12 col-md-12">
                <h3 class="heading">{{ module.name }}</h3>
                
                <div class="vcard">
					<img class="thumbnail" src="{% static 'img/empty_image.png' %}" alt="">
					<ul>
						<li class="v-heading">Module info</li>
						<li>
							<span class="item-key">Name</span>
							<div class="vcard-item">{{ module.name }}</div>
						</li>
						<li>
							<span class="item-key">Description</span>
							<div class="vcard-item">{{ module.description }}</div>
						</li>
				    </ul>
				</div> 
				
				<h3 class="heading">Lessons in {{ module.name }}</h3>
                
                
                <table class="table table-striped table-bordered table-condensed" data-rowlink="a">
                    <thead>
                        <tr>
                            <th>id</th>
                            <th>Name</th>
                            <th>Description</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for lesson in lesson_list %}
                    <tr>
                        <td>{{ lesson.id }}</td>
                        <td><a href="{% url 'lesson_detail' module.course.slug module.slug lesson.slug %}">{{ lesson.name }}</a></td>
                        <td>Some content goes here</td>
                        <td><a href="#">Edit</a> | <a href="#">Delete</a></td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
                
                <a href="{% url 'lesson_create' module.course.slug module.slug %}" class="btn btn-default">Add a lesson</a>
            </div>
            
            
        </div>                
    </div>
</div>
{% endblock body %}

jm_lms/templates/course/module_list.html
{% for module in module_list %}
BUGABUGA
{% endfor %}