jm_lms/apps/courses/urls.py
from django.conf.urls import patterns, url

from .views import  (CourseListView, 
                    CourseDetailView, 
                    ModuleListView, 
                    ModuleDetailView, 
                    LessonCreateView, 
                    LessonDetailView,
                    EnrolUserTemplateView)


def course_url(path):
    return r'^(?P<course_slug>[-\w\d]+){}'.format(path)
    
def module_url(path):
    return course_url(r'/(?P<module_slug>[-\w\d]+){}'.format(path))
    
def lesson_url(path):
    return module_url(r'/(?P<lesson_slug>[-\w\d]+){}'.format(path))

urlpatterns = patterns('',
    url(r'^$', CourseListView.as_view(), name='course_list'),
    url(course_url('/$'), CourseDetailView.as_view(), name='course_detail'),
    url(r'^module/$', ModuleListView.as_view(), name='module_list'),
    url(module_url('/$'), ModuleDetailView.as_view(), name='module_detail'),
    url(module_url('/lesson/create$'), LessonCreateView.as_view(), name='lesson_create'),
    url(module_url('/(?P<lesson_slug>[-\w\d]+)$'), LessonDetailView.as_view(), name='lesson_detail'),
    url(r'^enrol/(?P<userid>\d+)/(?P<courseid>\d+)/$', EnrolUserTemplateView.as_view(), name='enrol_to_course'),
)

jm_lms/apps/homesite/urls.py
from django.conf.urls import patterns, url

from .views import (home_page)


urlpatterns = patterns('',
    url(r'^$', home_page, name='homepage'),
)

jm_lms/apps/quiz/urls.py
from django.conf.urls import patterns, url

from .views import QuizListView, CategoriesListView,\
    ViewQuizListByCategory, QuizUserProgressView, QuizMarkingList,\
    QuizMarkingDetail, QuizDetailView, QuizTake


urlpatterns = patterns('',

                       url(regex=r'^$',
                           view=QuizListView.as_view(),
                           name='quiz_index'),

                       url(regex=r'^category/$',
                           view=CategoriesListView.as_view(),
                           name='quiz_category_list_all'),

                       url(regex=r'^category/(?P<category_name>[\w.-]+)/$',
                           view=ViewQuizListByCategory.as_view(),
                           name='quiz_category_list_matching'),

                       url(regex=r'^progress/$',
                           view=QuizUserProgressView.as_view(),
                           name='quiz_progress'),

                       url(regex=r'^marking/$',
                           view=QuizMarkingList.as_view(),
                           name='quiz_marking'),

                       url(regex=r'^marking/(?P<pk>[\d.]+)/$',
                           view=QuizMarkingDetail.as_view(),
                           name='quiz_marking_detail'),

                       #  passes variable 'quiz_name' to quiz_take view
                       url(regex=r'^(?P<slug>[\w-]+)/$',
                           view=QuizDetailView.as_view(),
                           name='quiz_start_page'),

                       url(regex=r'^(?P<quiz_name>[\w-]+)/take/$',
                           view=QuizTake.as_view(),
                           name='quiz_question'),
)

jm_lms/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView

from apps.accountusers.views import LoginView, LogoutView, RegisterView, EmailSentView, ActivationView, NewUserRegistrationAPI
from apps.registrations.views import ProspectiveUserList, ProspectiveUserDetail


urlpatterns = [
    # Examples:
    # url(r'^$', 'project_name.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    
    url(r'^summernote/', include('django_summernote.urls')),
    
    # Pesapal processing url
    url(r'^payments/', include('django_pesapal.urls')),
    
    #url(r'^$', TemplateView.as_view(template_name='homepage.html')),
    
    url(r'^', include('jm_lms.apps.homesite.urls', namespace='home')), # Directing root url to a different app
    url(r'^dashboard/', include('jm_lms.apps.dashboard.urls')),
    url(r'^course/', include('jm_lms.apps.courses.urls')),
    url(r'^exercise/', include('jm_lms.apps.exercises.urls')),
    url(r'^purchase/', include('jm_lms.apps.purchase.urls', namespace='purchase')),
    url(r'^askaquestion/', include('jm_lms.apps.askaquestion.urls', namespace='askaquestion')),
    
    # user authentication and registration
    url(r'^login/', LoginView.as_view(), name='login'),
    url(r'^logout/', LogoutView.as_view(), name='logout'),
    url(r'^register/', RegisterView.as_view(), name='register'),
    url(r'^registration_email_sent\.html', EmailSentView.as_view(), name='confirmation_mail_sent'),
    url(r'^user_activation\.html', ActivationView.as_view(), name='activation'),
    url(r'^terms_and_conditions\.html', TemplateView.as_view(template_name='terms_conditions.html')),
    
    # Quiz links
    url(r'^quiz/', include('jm_lms.apps.quiz.urls')),
    
    # REST API for new signups
    url(r'^pusers/', ProspectiveUserList.as_view()),
    url(r'^pusers/(?P<pk>[0-9]+)/$', ProspectiveUserDetail.as_view()),
    url(r'^newreg/', NewUserRegistrationAPI.as_view()),

    url(r'^admin/', include(admin.site.urls)),
]

jm_lms/apps/analytics/models.py
from django.db import models

# Create your models here.

jm_lms/apps/askaquestion/models.py
from django.conf import settings
from django.db import models
from django.template.defaultfilters import slugify
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _
from jm_lms.apps.courses.models import Lesson


class QuestionAsked(models.Model):
    title = models.CharField(_("Question Title"), max_length=120)
    body = models.TextField(_("Question Description"))
    sender = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='asked_questions', verbose_name=_("Sender"))
    lesson = models.ForeignKey(Lesson)
    parent_question = models.ForeignKey('self', related_name='next_questions', null=True, blank=True, verbose_name=_("Parent question"))
    sent_at = models.DateTimeField(_("sent at"), auto_now_add=True, null=True, blank=True)
    read_at = models.DateTimeField(_("read at"), null=True, blank=True)
    replied_at = models.DateTimeField(_("replied at"), null=True, blank=True)
    slug = models.SlugField(editable=False)
    answer = models.TextField(_("Question's Answer"), null=True, blank=True)
    
    

    
    class Meta:
        ordering = ['-sent_at']
        verbose_name = _("Question Asked")
        verbose_name_plural = _("Questions Asked")
        
    def __unicode__(self):
        return self.title
        
    def save(self, *args, **kwargs):
        if not self.id:
            slug = slugify(self.title)
            new_slug = slug
            count = 0
            while QuestionAsked.objects.filter(slug=new_slug).exclude(id=self.id).count() > 0:
                count += 1
                new_slug = '{slug}-{count}'.format(slug=slug, count=count)
            self.slug = new_slug
            
        super(QuestionAsked, self).save(*args, **kwargs)
        
    def get_absolute_url(self):
        return reverse('askedquestion_detail', args=[self.slug])

jm_lms/apps/courses/models.py
import logging

from django.conf import settings
from django.db import models
from django.db.models import Sum
from django.template.defaultfilters import slugify
from django.utils.translation import ugettext_lazy as _

from positions.fields import PositionField

from jm_lms.apps.exercises.models import Exercise
from jm_lms.apps.quiz.models import Quiz



log = logging.getLogger(__name__)


NOT_STARTED = 0
IN_PROGRESS = 1
COMPLETED = 2
PROGRESS_STATUS = (
    (NOT_STARTED, _("Not Started")),
    (IN_PROGRESS, _("In Progress")),
    (COMPLETED, _("Completed"))
)


class Course(models.Model):
    """
    Data model representing a course.
    A course can have one or more modules.
    """
    name = models.CharField(verbose_name=_("Course Name"), max_length=200, help_text=_('The course title'))
    description = models.TextField(verbose_name="Course Description", help_text=_("Course description"))
    prerequisite = models.ForeignKey('self', verbose_name=_("Prerequisite Course"), null=True, blank=True, default=None)   
    slug = models.SlugField(editable=False, help_text=_('Unique identifier'))
    position = PositionField(collection='prerequisite')
    position_order = models.IntegerField(verbose_name=_("Order to be shown in views"), default=0)
    
    class Meta:
        verbose_name_plural = "Courses"
        
    def __unicode__(self):
        return self.name
        
    def get_absolute_url(self):
        return reverse('course_detail', args=[self.slug])
        
    def save(self, *args, **kwargs):
        if not self.id:
            slug = slugify(self.name)
            new_slug = slug
            count = 0
            while Course.objects.filter(slug=new_slug).exclude(id=self.id).count() > 0:
                count += 1
                new_slug = '{slug}-{count}'.format(slug=slug, count=count)
            self.slug = new_slug
            
        super(Course, self).save(*args, **kwargs)
        
    @property    
    def previous_course(self):
        if self.prerequisite is None:
            return Course.objects.None()
        return self.prerequisite
        
    def _student_count(self):
        raise NotImplementedError
        
    @classmethod
    def get_student_progress_in_course(cls, student, course):
        """
        Calculates the progress of the given student in a particular course.
        This is achieved by summing up the module progress of the student.
        """
        progress = 0
        try:
            course = Course.objects.get(pk=course.pk)
            course_modules = course.module_set.all()
            num_of_modules_in_course = course_modules.count()
            
            # Current progress of all the modules done by a student
            curr_module_progress_total = 0
            for module in course_modules:
                curr_module_progress_total += Module.get_student_progress_in_module(student, module)
                
            # Calculate current course progress of the student
            progress = (100*curr_module_progress_total)/(num_of_modules_in_course*100)
        except ZeroDivisionError:
            progress = 0
        return progress
        
    @property    
    def has_previous_course(self):
        if self.prerequisite:
            return True
        return False
        
    def is_previous_course_done(self, student):
        """
        Determine if a previous course has been completed by student.
        """
        if not self.has_previous_course:
            return True
        elif self.has_previous_course:
            try:
                total_course_score = StudentLessonProgress.objects.filter(student=student, lesson__module__course=self.prerequisite).aggregate(total_percentage=Sum('done_percent'))
                course_score_result = total_course_score.get('total_percentage', 0)
                
                student_course_progress = (course_score_result*100) / (self.prerequisite.module_set.all().count()*100)
                
                if student_course_progress >= 100:
                    return True
            except (StudentLessonProgress.DoesNotExist, ZeroDivisionError, TypeError):
                return False            
        return False
    

class Module(models.Model):
    DRAFT = 1
    SUSPENDED = 2
    PUBLISHED = 3
    MODULE_STATUSES = (
        (DRAFT, _("Draft")),
        (SUSPENDED, _("Suspended")),
        (PUBLISHED, _("Published"))
    )
    course = models.ForeignKey(Course)
    name = models.CharField(verbose_name=_("Module Name"), max_length=200, help_text=_('The module title'))
    description = models.TextField(verbose_name="Module Description", help_text=_("Module description"))
    prerequisite = models.ForeignKey('self', verbose_name=_("Prerequisite Module"), null=True, blank=True, default=None)   
    slug = models.SlugField(editable=False, help_text=_('Unique identifier'))
    status = models.IntegerField(verbose_name="Module Status", choices=MODULE_STATUSES, default=PUBLISHED)
    position = PositionField(collection='course', default=0)
    end_of_module = models.TextField(verbose_name=_("Module Summary"), default=None, null=True, help_text=_("Wrap and summarize this module"))
    last_module = models.ForeignKey('self', verbose_name=_("Previous Module"), null=True, blank=True, default=None, related_name="previous_module")
    next_module = models.ForeignKey('self', verbose_name=_("Next Module"), null=True, blank=True, default=None, related_name="the_next_module")
    

    class Meta:
        verbose_name_plural = "Modules"
        
    def __unicode__(self):
        return self.name
        
    def get_absolute_url(self):
        return reverse('module_detail', args=[self.slug])
        
    def save(self, *args, **kwargs):
        if not self.id:
            slug = slugify(self.name)
            new_slug = slug
            count = 0
            while Module.objects.filter(slug=new_slug).exclude(id=self.id).count() > 0:
                count += 1
                new_slug = '{slug}-{count}'.format(slug=slug, count=count)
            self.slug = new_slug           
            
        super(Module, self).save(*args, **kwargs)
        
    @classmethod
    def get_student_progress_in_module(cls, student, module):
        """
        Calculates the progress of the given student in a particular module.
        This is achieved by summing up the lesson progress of the student.
        """
        progress = 0
        try:
            if module:
                module = Module.objects.get(pk=module.pk)
                module_lessons = module.lesson_set.all()
                num_of_lessons_in_module = module_lessons.count()
                # last_lesson_in_module = [index for index, item in enumerate(module_lessons)[len(module_lessons)-1::]]
                # a = module_lessons.order_by('id')
                # b = list(a.values_list('id', flat=True)).index(obj.id)
                # last_lesson = b[len(b)-1::]

                # Current progress of all the lessons done by a student
                curr_lesson_progress_total = 0
                for lesson in module_lessons:
                    curr_lesson_progress_total += Lesson.get_student_progress_in_lesson(student, lesson)

                # Calculate current module progress of the student
                progress = (100*curr_lesson_progress_total)/(num_of_lessons_in_module*100)
        except ZeroDivisionError, AttributeError:
            progress = 0
        return progress

    # @classmethod
    # def get_last_lesson_in_module(cls, student, module):
    #     last_lesson = Module.objects.raw(
    #         "select * from courses_lesson where module_id in (select module_id from courses_lesson group by module_idhaving count (*) > 1)"
    #      )
    #
    #     # if module:
    #     #     module = Module.objects.get(pk=module.pk)
    #     #     module_lessons = module.lesson_set.all()
    #     #     last_lesson_in_module = module_lessons[-1]
    #     return last_lesson

        
    @property    
    def has_previous_module(self):
        if self.prerequisite:
            return True
        return False

        
    def is_previous_module_done(self, student):
        """
        Determine if a previous module has been completed by student.
        """
        if not self.has_previous_module:
            return True
        elif self.has_previous_module:
            try:
                total_module_score = StudentLessonProgress.objects.filter(student=student, lesson__module=self.prerequisite).aggregate(total_percentage=Sum('done_percent'))
                module_score_result = total_module_score.get('total_percentage', 0)
                
                student_module_progress = (module_score_result*100) / (self.prerequisite.lesson_set.all().count()*100)
                
                if student_module_progress >= 100:
                    return True
            except (StudentLessonProgress.DoesNotExist, ZeroDivisionError, TypeError):
                return False            
        return False
        




class Lesson(models.Model):
    module = models.ForeignKey(Module)
    name = models.CharField(verbose_name=_("Lesson Title"), max_length=200, help_text=_('The lesson title'))
    prerequisite = models.ForeignKey('self', verbose_name=_("Prerequisite Lesson"), null=True, blank=True, default=None)   
    content = models.TextField()
    instructions_before = models.TextField(verbose_name=_("Instructions before exercise"), null=True, blank=True, default=None)
    instructions_after = models.TextField(verbose_name=_("Instructions after exercise"), null=True, blank=True, default=None)
    quizzes = models.ManyToManyField(Quiz, verbose_name=_("Quiz"), blank=True, related_name='lessons')
    slug = models.SlugField(editable=False, help_text=_('Unique identifier'))
    exercises = models.ManyToManyField(Exercise, verbose_name=_("Exercise"), blank=True, related_name='lesson_exercises')

jm_lms/apps/dashboard/models.py
from django.db import models

# Create your models here.

jm_lms/apps/homesite/models.py
from django.db import models

# Create your models here.

jm_lms/apps/askaquestion/forms.py
from django.forms import ModelForm
from .models import QuestionAsked


class AskQuestionForm(ModelForm):
    class Meta:
        model = QuestionAsked
        fields = ['title', 'body', 'lesson']

jm_lms/apps/courses/forms.py
from django import forms

from .models import LessonQuestion

class LessonQuestionForm(forms.ModelForm):

    class Meta:
        model = LessonQuestion
        fields = ('title', 'description',)

jm_lms/apps/analytics/views.py
from django.shortcuts import render

# Create your views here.

jm_lms/templates/dashboard/ask_lesson_question.html
{% extends "base_generic_student.html" %}
{% load staticfiles %}
{% load has_group %}

{% block title %}Ask a question{% endblock %}

{% block body %}
<div id="contentwrapper">
    <div class="main_content">
        <div id="jCrumbs" class="breadCrumb module">
            <ul>
                <li>
                    <a href="{% url 'student_dashboard' %}"><i class="glyphicon glyphicon-home"></i></a>
                </li>
            </ul>
        </div>	
               
        <div class="row">
            <div class="col-sm-12 col-md-12">
                <h3 class="heading">Ask a question</h3>
                               
                <form method="POST" action="{% url 'lesson_question_new' lesson.module.course.slug lesson.module.slug lesson.slug %}">
                    {% csrf_token %}
			        <div class="formSep">
				
			        </div>
			        
			        {{ form.non_field_errors }}
			        
			        <div class="formSep">
				        <div class="row">
					        <div class="col-sm-12 col-md-12">
						        {{ form.title.errors }}
						        <label>Question Title <span class="f_req">*</span></label>
						        <input class="form-control" type="text" id="id_title" name="title">
						        {% if form.title.help_text %}
						        <span class="help-block">{{ form.title.help_text|safe }}</span>
						        {% endif %}
					        </div>
					        
					        <div class="col-sm-12 col-md-12">
					            {{ form.description.errors }}
						        <label>Question Details <span class="f_req">*</span></label>
						        <textarea cols="10" rows="3" class="form-control" id="id_description" name="description"></textarea>
					        </div>					        
				        </div>
			        </div>
			        
			        <div class="form-actions">
				        <button class="btn btn-primary" type="submit">Submit Question</button>
			        </div>
			    </form>
                
		    </div>
        </div> 
                       
    </div>
</div>
{% endblock body %}

jm_lms/templates/dashboard/dashboard.html
{% extends "base_generic.html" %}
{% load staticfiles %}

{% block title %}Dashboard{% endblock %}

{% block body %}
<div id="contentwrapper">
    <div class="main_content">
        <div id="jCrumbs" class="breadCrumb module">
            <ul>
                <li>
                    <a href="{% url 'dashboard' %}"><i class="glyphicon glyphicon-home"></i></a>
                </li>
            </ul>
        </div>	
        <div class="row">
            
            <div class="col-sm-12 col-md-12">
                <h3 class="heading">Dashboard</h3>
                
            </div>
            
            
        </div>                
    </div>
</div>
{% endblock body %}

jm_lms/templates/dashboard/employer_dashboard.html
{% extends "base_generic_employer.html" %}
{% load staticfiles %}

{% block title %}Dashboard{% endblock %}

{% block body %}
<div id="contentwrapper">
    <div class="main_content">
        <div id="jCrumbs" class="breadCrumb module">
            <ul>
                <li>
                    <a href="{% url 'employer_dashboard' %}"><i class="glyphicon glyphicon-home"></i></a>
                </li>
            </ul>
        </div>	
        <div class="row">
            <div class="col-sm-12 col-md-12">
                <h3 class="heading">Candidates</h3>
                <div class="btn-group sepH_b">
			        <button data-toggle="dropdown" class="btn dropdown-toggle btn-default btn-sm">Action <span class="caret"></span></button>
			        <ul class="dropdown-menu">
				        <li><a href="tables_more.html#" class="delete_rows_simple" data-tableid="smpl_tbl"><i class="icon-trash"></i> Delete</a></li>
				        <li><a href="javascript:void(0)">Export as CSV</a></li>
				        <li><a href="javascript:void(0)">Export as PDF</a></li>
			        </ul>
                </div>
                
                <table class="table table-bordered table-striped" id="smpl_tbl">
			        <thead>
				        <tr>
					        <th class="table_checkbox"><input name="select_rows" class="select_rows" data-tableid="smpl_tbl" type="checkbox"></th>
					        <th>id</th>
					        <th>Candidate</th>
					        <th>Course</th>
					        <th>Date Enrolled</th>
					        <th>Status</th>
				        </tr>
			        </thead>
			        <tbody>
			            {% for enrollment in active_enrollments %}
				        <tr>
					        <td><input name="row_sel" class="select_row" type="checkbox"></td>
					        <td>{{ enrollment.student.id }}</td>
					        <td>{{ enrollment.student.get_full_name }}</td>
					        <td><a href="{% url 'course_detail' enrollment.course.slug %}">{{ enrollment.course.name }}</a></td>
					        <td>{{ enrollment.created }}</td>
					        <td>In Progress</td>
				        </tr>
				        {% endfor %}
			        </tbody>
		        </table>
		    </div>
        </div>   
        
        
        
        <!-- Candidates pagination -->
        <div class="row">
            <div class="col-sm-5">
                <div class="dataTables_info" id="dt_gal_info">Showing 1 to 6 of 6 entries</div>
            </div>
            <div class="col-sm-7">
                <div class="dataTables_paginate paging_bootstrap">
                    <ul class="pagination pagination-sm">
                        <li class="prev disabled"><a href="#">Previous</a></li>
                        <li class="active"><a href="#">1</a></li>
                        <li class="next disabled"><a href="#">Next</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <!-- End of pagination -->
        
        
        <!-- Job Postings-->
        <div class="row">
            <div class="col-sm-12 col-md-12">
                <h3 class="heading">My Job Posts</h3>
                <div class="btn-group sepH_b">
			        <button data-toggle="dropdown" class="btn dropdown-toggle btn-default btn-sm">Action <span class="caret"></span></button>
			        <ul class="dropdown-menu">
				        <li><a href="tables_more.html#" class="delete_rows_simple" data-tableid="smpl_tbl"><i class="icon-trash"></i> Delete</a></li>
				        <li><a href="javascript:void(0)">Export as CSV</a></li>
				        <li><a href="javascript:void(0)">Export as PDF</a></li>
			        </ul>
                </div>
                <table class="table table-bordered table-striped" id="smpl_tbl">
			        <thead>
				        <tr>
					        <th class="table_checkbox"><input name="select_rows" class="select_rows" data-tableid="smpl_tbl" type="checkbox"></th>
					        <th>id</th>
					        <th>Job</th>
					        <th>Type</th>
					        <th>Date Posted</th>
				        </tr>
			        </thead>
			        <tbody>
			            {% for job in my_jobs %}
				        <tr>
					        <td><input name="row_sel" class="select_row" type="checkbox"></td>
					        <td>{{ job.id }}</td>
					        <td><a href="#">{{ job.title }}</a></td>
					        <td>{{ job.type }}</td>
					        <td>{{ job.date_posted }}</td>
				        </tr>
				        {% endfor %}
			        </tbody>
		        </table>
            </div>
        </div>   
        
                     
    </div>
</div>
{% endblock body %}

jm_lms/templates/dashboard/questions_asked.html
{% extends "base_generic_student.html" %}
{% load staticfiles %}
{% load has_group %}

{% block title %}Dashboard{% endblock %}

{% block body %}
<div id="contentwrapper">
    <div class="main_content">
        <div id="jCrumbs" class="breadCrumb module">
            <ul>
                <li>
                    <a href="{% url 'student_dashboard' %}"><i class="glyphicon glyphicon-home"></i></a>
                </li>
            </ul>
        </div>	
               
        <div class="row">
            <div class="col-sm-12 col-md-12">
                <h3 class="heading">My Questions</h3>
                               
                {% if student_lesson_questions %}
                <table class="table table-bordered table-striped" id="smpl_tbl">
			        <thead>
				        <tr>
					        <th class="table_checkbox"><input name="select_rows" class="select_rows" data-tableid="smpl_tbl" type="checkbox"></th>
					        <th>Title</th>
					        <th>Lesson</th>
					        <th>Status</th>
					        <th>Date Asked</th>
				        </tr>
			        </thead>
			        <tbody>
			            {% for question in student_lesson_questions %}
				        <tr>
					        <td><input name="row_sel" class="select_row" type="checkbox"></td>
					        <td><a href="#">{{ question.title }}</a></td>
					        <td><a href="{% url 'learn_lesson' question.lesson.module.course.slug question.lesson.module.slug question.lesson.slug %}">{{ question.lesson.name }}</a></td>
					        <td>{{ question.get_status_display }}</td>
					        <td>{{ question.date_asked }}</td>
				        </tr>
				        {% endfor %}
			        </tbody>
		        </table>
		        {% else %}
		        No questions have been asked so far.
		        {% endif %}
		    </div>
        </div>
        
        

                       
    </div>
</div>
{% endblock body %}

jm_lms/templates/dashboard/student_lessons.html
{% extends "base_site.html" %}
{% load staticfiles %}
{% load has_group %}

{% block title %}Lessons{% endblock %}

{% block body %}

<!-- Section show current page and breadcrumb -->
<section class="page-indecator">
    <div class="container">
        <h2 class="heading">Module: {{ module.name }}</h2>
        <!-- Breadcrumb pattern -->
        <ol class="breadcrumb">
            <li><a href="{% url 'student_dashboard' %}">Home</a></li>
            <li><a href="{% url 'student_modules' module.course.slug %}">{{ module.course.name }}</a></li>
            <li class="active">{{ module.name }}</li>
        </ol>
        <!-- Default one color divider -->
        <div class="divider"></div>
    </div>
</section> <br><br><br>
<!-- end section show current page and breadcrumb -->

<section>
    <div class="container">
        <div class="row">
        <div class="col-sm-12">
                                
                <p>{{ module.description|safe }}</p>

                <h4 class="heading">Lessons you will learn</h4>
                
                <div class="tabs tabs--minimal present-addition-lg">
                
                    <!-- Nav tabs -->
                    <ul class="nav nav-tabs">
                        <li class="active"><a href="#one" data-toggle="tab">Lessons</a></li>
                    </ul>
                    <!-- Tab panes -->
                    
                    <div class="tab-content">
                        <div class="tab-pane active" id="one">
                        
            <!-- Target table for specific needs -->
            <div class="table-responsive">
                <table class="table table--target table--mod table--target table--forum">
                    <thead>
                        <tr>
                            <th class="table-main">Lesson title</th>
                            <th class="table-main">Status</th>
                            <th class="table-main">Progress</th>
                        </tr>
                    </thead>
                    <tbody>
                    
                    {% for lesson in lesson_list %}
                        <tr>
                            <td>
                                <div class="table__category-photo table__category-photo--markered">
                                    <img src="{% static 'theme/images/training-icon.jpg' %}" alt="">
                                </div>
                                
                                {% if lesson.is_accessible %}
                                    <a class="table__category" href="{% url 'learn_lesson' lesson.module.course.slug lesson.module.slug lesson.slug %}">{{ lesson.name }}</a>
                                {% else %}
                                    {{ lesson.name }}
                                {% endif %}
                                
                            </td>
                            <td>{{ lesson.status }}</td>
                            <td> 
                                <div class="progress-container progress--secondary progress-cut" id="progress-start">
                                    <div class="progress-quantity">Progress: <span class="progress-value">{{ lesson.done_percent }}</span>%</div>
                                    <div class="progress" data-level="{{ lesson.done_percent }}">
                                        <div class="progress-bar" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: {{ lesson.done_percent }}%;"></div>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                        
                    </tbody>
                </table>
            </div>
            <!-- end responsive table -->
                            
                        </div>
                        <div class="tab-pane" id="two">
						                    
                         
                        </div>
                        
                                                  </div>
                    </div>
                </div>
                <!-- end tabs -->
        
            <!-- end col -->

</div>

        <!-- end col -->
        </div>
        <!-- end row -->
    </div>
    <!-- end container -->
</section>


{% endblock body %}